version: '3'
# 参考: https://qiita.com/hgaiji/items/edf71435d0565257f980
# 実行: docker-compose up - d
services:
  jupyter:
    build: .
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 8888:8888
    volumes: # [ホスト:コンテナ]間の共有フォルダ
      - /Users/ryomanakagawa/prac/docker_work_dir:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''